name: Litton7
channels:
  - nvidia
  - pytorch
dependencies:
  - pytorch>=2.0.*
  - torchvision
  # change pytorch-cuda's version to equal or lower than your CUDA version
  # available choices: 11.8, 12.1
  - pytorch-cuda=11.8
  - conda-forge::pillow
  - conda-forge::tqdm
